language: php

php:
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - mkdir -p build/logs
  - composer ci

after_script:
  - php vendor/bin/php-coveralls -v